config/routes.rb
Rails.application.routes.draw do
  resources :clinics

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clinic.rb
class Clinic < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clinics_controller.rb
class ClinicsController < ApplicationController
  before_action :set_clinic, only: [:show, :edit, :update, :destroy]

  # GET /clinics
  # GET /clinics.json
  def index
    @clinics = Clinic.all
  end

  # GET /clinics/1
  # GET /clinics/1.json
  def show
  end

  # GET /clinics/new
  def new
    @clinic = Clinic.new
  end

  # GET /clinics/1/edit
  def edit
  end

  # POST /clinics
  # POST /clinics.json
  def create
    @clinic = Clinic.new(clinic_params)

    respond_to do |format|
      if @clinic.save
        format.html { redirect_to @clinic, notice: 'Clinic was successfully created.' }
        format.json { render :show, status: :created, location: @clinic }
      else
        format.html { render :new }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clinics/1
  # PATCH/PUT /clinics/1.json
  def update
    respond_to do |format|
      if @clinic.update(clinic_params)
        format.html { redirect_to @clinic, notice: 'Clinic was successfully updated.' }
        format.json { render :show, status: :ok, location: @clinic }
      else
        format.html { render :edit }
        format.json { render json: @clinic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clinics/1
  # DELETE /clinics/1.json
  def destroy
    @clinic.destroy
    respond_to do |format|
      format.html { redirect_to clinics_url, notice: 'Clinic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clinic
      @clinic = Clinic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clinic_params
      params.require(:clinic).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinics_helper.rb
module ClinicsHelper
end

app/views/clinics/_form.html.haml
= form_for @clinic do |f|
  - if @clinic.errors.any?
    #error_explanation
      %h2= "#{pluralize(@clinic.errors.count, "error")} prohibited this clinic from being saved:"
      %ul
        - @clinic.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/clinics/edit.html.haml
%h1 Editing clinic

= render 'form'

= link_to 'Show', @clinic
\|
= link_to 'Back', clinics_path

app/views/clinics/index.html.haml
%h1 Listing clinics

%table
  %thead
    %tr
      %th Title
      %th
      %th
      %th

  %tbody
    - @clinics.each do |clinic|
      %tr
        %td= clinic.title
        %td= link_to 'Show', clinic
        %td= link_to 'Edit', edit_clinic_path(clinic)
        %td= link_to 'Destroy', clinic, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Clinic', new_clinic_path

app/views/clinics/new.html.haml
%h1 New clinic

= render 'form'

= link_to 'Back', clinics_path

app/views/clinics/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @clinic.title

= link_to 'Edit', edit_clinic_path(@clinic)
\|
= link_to 'Back', clinics_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>